apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: app
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-secret
  data:
    - secretKey: username
      remoteRef:
        key: secret/postgres
        property: username
    - secretKey: password
      remoteRef:
        key: secret/postgres
        property: password
    - secretKey: database
      remoteRef:
        key: secret/postgres
        property: database
