apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter-metrics
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - app
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-postgres-exporter
      app.kubernetes.io/instance: postgres-exporter
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
